name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    - name: First interaction
    uses: actions/first-interaction@v1.2.0
    with:
      # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
      repo-token: 
      # Comment to post on an individual's first issue
      issue-message: # optional
      # Comment to post on an individual's first pull request
      pr-message: # optional

    - name: KSOC Guard
  # You may pin to the exact commit or the version.
  # uses: ksoclabs/guard-action@e61edd337d11df1ec4f8d5279f2f9937a7d1dadc
  uses: ksoclabs/guard-action@v0.0.10
  with:
    # The severity level at which to fail the workflow. Valid values are: none, low, medium, high, critical.
    fail_on_severity: # optional, default is none
    # The format of the output. Valid values are: ci-table, table.
    format: # optional, default is ci-table
    # Comma separated list of paths to ignore.
    ignored_paths: # optional
    # Comma separated list of policy IDs to ignore.
    ignored_policies: # optional
    # The KSOC access key ID.
    ksoc_access_key_id: # optional
    # The KSOC account ID.
    ksoc_account_id: # optional
    # The KSOC API URL.
    ksoc_api_url: # optional, default is https://api.ksoc.com
    # The KSOC secret key.
    ksoc_secret_key: # optional
    # Comma separated list of paths to scan.
    paths: # optional, default is .
    # The directory containing the policies to execute.
    policy_dir: # optional
    # Comma separated list of policy IDs to execute.
    policy_ids: # optional
    # Comma separated list of policy tags to execute.
    policy_tags: # optional
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    
